config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  resources :dokuments do
    collection do
        post ':id/addKorisnik', :to =>  'dokuments#addKorisnik', :as => :addKorisnik

    end
    resource :izmenas do
      collection do
        post "rollback", :to=> 'izmenas#rollback', :as => :rollback
      end
    end
  end

  resources :users do
    collection do
      delete "obrisiUsera", :to=> 'users#obrisi', :as => :obrisi
      post "makeAdmin", :to=> 'users#makeAdmin', :as => :makeAdmin

    end
  end



  root "posts#index"

end

app/models/dokument.rb
class Dokument < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tranzakcijas
  has_many :primedbas
  has_many :izmenas
end

app/controllers/dokuments_controller.rb
class DokumentsController < ApplicationController

  def index
    @user = User.find(current_user.id)
    @dokuments = Dokument.joins(:users).where('users.id = :user_id', user_id: current_user.id)
  end

  def new
    @dokument = Dokument.new
  end

  def create
    # @users = User.find(current_user.id)
    # @dokument = @users.dokuments.create(dokument_params.permit(:title, :content))

    @dokument = Dokument.new(dokument_params)
    current_user.dokuments << @dokument
    if @dokument.save
      redirect_to @dokument
    else
      render 'new'
    end
  end


  def show
    @user = User.find(current_user.id)
    dokuments = Dokument.joins(:users).where('users.id = :user_id', user_id: current_user.id)

    puts dokuments

    dokuments.class
    dokuments.first
    dokuments.class
    brojDokumenata = 0

    for x in dokuments do
      puts x.id
      puts params[:id]
      if x.id.to_s == params[:id].to_s
        puts "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        brojDokumenata+=1
      end
    end

    puts brojDokumenata

    if brojDokumenata != 0
      @dokument = Dokument.find(params[:id])
      @users = User.joins(:dokuments).where('dokuments.id = :dokument_id', dokument_id: params[:id])
    else
      redirect_to root_path
    end
  end

  def update
    @dokument = Dokument.find(params[:id])
    izmenaParametri = izmena_params
    izmenaParametri[:user_id] = current_user.id
    if (@izmena = @dokument.izmenas.create(izmenaParametri))
      if @dokument.update(dokument_params)
        redirect_to @dokument

      else
        render 'edit'
      end

    else
      render 'edit'

    end
  end

  def edit
    @dokument = Dokument.find(params[:id])

  end

  def destroy
    @dokument = Dokument.find(params[:id])
    @dokument.destroy

    redirect_to dokuments_path

  end

  def addKorisnik
    puts params[:q]
    @user = User.find_by_email(params[:q])
    @dokument = Dokument.find(params[:id])
    if @user != nil
      begin
        query = "INSERT INTO dokuments_users(user_id,dokument_id) VALUES(#{@user.id},#{params[:id]})"
        ActiveRecord::Base.connection.execute(query)
        rescue ActiveRecord::RecordNotUnique
          redirect_to root_path

      end

      redirect_to @dokument
    end
  end



  private



  def dokument_params
    params.require(:dokument).permit(:title, :content)
  end

  def izmena_params

    params.require(:dokument).permit(:title, :content, :id)
  end

end

app/helpers/dokuments_helper.rb
module DokumentsHelper
end

app/views/dokuments/_form.erb
<div class="section">
  <%= simple_form_for @dokument do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, as: :text, input_html: { class: 'textarea' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary" %>
  <% end %>
</div>

app/views/dokuments/edit.erb
<%= render 'form' %>

app/views/dokuments/index.erb
<section class="section">
  <div class="container">
    <% @dokuments.each do |dokument|  %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"> <%= link_to dokument.title, dokument %></p>
            </div>
          </div>
          <div class="content">
            <%= dokument.content %>
          </div>
<!--          <div class="comment-count">-->
<!--            <span class="tag is-rounded"> <%## comment.count %></span>-->
<!--          </div>-->
        </div>
      </div>
      <br>

    <% end %>
  </div>
</section>

app/views/dokuments/new.erb
<style>
  #kontejner{
    text-align: center;
  }

</style>

<div class="container" id="kontejner">
  <h1 class="title "> Kako zelite da napravite novi dokument?</h1>


  <%= render 'form' %>


</div>

app/views/dokuments/show.erb
<style>
  #paragraf{
    padding: 10px;
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
  #dugme{
    margin: 0px 10px 10px 10px;

  }
    #textfield{
      margin-bottom: 10px;
      max-width: 150px;
    }

    .dugmici{
      margin-bottom: 10px;
    }



</style>

<section class="section">
  <div class="container">

    <nav class="level">
      <div class="level-left">
        <p class="level-item">
          <strong>Opcije</strong>
        </p>

        <p class="level-item">
          <%=  link_to "Pogledaj izmene", dokument_izmenas_path(@dokument), class: "button dugmici" %>

        </p>


      </div>

      <div class="level-right">
       <!-- <%#= form_for @dokument, url:addKorisnik_dokuments_path do |f| %>
          <div class="text-field">
            <div class="control">
              <%#= f.text_field :content, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
            </div>
          </div>

          <%#= f.button :submit, class: "button is-primary" %>
          <%# end %>-->
        <p class="level-item">
        <%= form_tag(addKorisnik_dokuments_path, :method => "post") do %>
          <%= label_tag(:q, "Search for:",:id=>"labela", :class=>"nesto ", :name=>"labela") %>
          <%= email_field_tag(:q ,"",:id=>"textfield", :class=>"input dugmici ", :name=>"q") %>
          <%= submit_tag("Add user", :id=>"dugme", :class=>"button dugmici", :name=>"submit")  %>
        <% end %>
        </p>

  <!--      <p class="level-item">
          <%#= link_to "Dodaj kolaboratora", dokument_addKorisnik_path(@dokument), class:"button" %>

        </p>-->
        <p class="level-item">
          <%=  link_to "Edit", edit_dokument_path(@dokument), class: "button dugmici" %>
        </p>

        <p class="level-item">
          <%= link_to "Delete", dokument_path(@dokument), method: :delete, data: {confirm: "Da li ste sigurni?"}, class:"button is-danger dugmici" %>
        </p>
      </div>
    </nav>
    <hr>


    <h2 class="title"><%= @dokument.title %></h2>
    <div class="content" id="paragraf">
      <%= simple_format(@dokument.content)  %>
    </div>


    <h2 class="title is-5">Vlasnici ovog dokumenta:</h2>

    <div class="list ">
    <% @users.each do |user| %>
        <a class="list-item"> <%=user.email %></a>
    <% end %>
    </div>
  </div>
</section>