config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  resources :dokuments do
    collection do
        post ':id/addKorisnik', :to =>  'dokuments#addKorisnik', :as => :addKorisnik

    end
    resource :izmenas do
      collection do
        post "rollback", :to=> 'izmenas#rollback', :as => :rollback
      end
    end
  end

  resources :users do
    collection do
      delete "obrisiUsera", :to=> 'users#obrisi', :as => :obrisi
      post "makeAdmin", :to=> 'users#makeAdmin', :as => :makeAdmin

    end
  end



  root "posts#index"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    #

    can :read, :all # permissions for every user, even if not logged in
    if user.present?  # additional permissions for logged in users (they can manage their posts)
      can :manage, Post, user_id: user.id
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/dokument.rb
class Dokument < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tranzakcijas
  has_many :primedbas
  has_many :izmenas
end

app/models/izmena.rb
class Izmena < ApplicationRecord
  belongs_to :user
  belongs_to :dokument
end

app/models/organizacija.rb
class Organizacija < ApplicationRecord
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  belongs_to :user

end

app/models/primedba.rb
class Primedba < ApplicationRecord
  belongs_to :user
  belongs_to :dokument
end

app/models/tranzakcija.rb
class Tranzakcija < ApplicationRecord
  belongs_to :user
  has_one :dokument
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :posts
  has_and_belongs_to_many :dokuments
  has_many :primedbas
  has_many :izmenas

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :content))
    redirect_to post_path(@post)
  end


  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end
end

app/controllers/izmenas_controller.rb
class IzmenasController < ApplicationController

  def index
    @izmenas = Izmena.find_by_dokument_id(params[:id])
  end

  def new
    @izmena = Izmena.new
  end

  def rollback
    @izmena = Izmena.find(params[:nesto])
    @dokument = Dokument.find(params[:dokument_id])
    @dokument.update(title:@izmena.title, content:@izmena.content)
    redirect_to @dokument
  end

  def show
    puts "DOSAO JE OVDEEEEEEEEEEEEEEEEEEEEEE"

    @izmenas = Izmena.where(dokument_id: params[:dokument_id]).all
  end

  def destroy
    @izmena = Izmena.find(params[:id])
    @izmena.destroy

    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    #@user = User.find(params[:user_id])
    #@post = current_user.posts.new(params[:post])
    #@post = current_user.posts.find(post_params[:id])
    @user = User.find(current_user.id)
    @post = @user.posts.create(post_params.permit(:title, :content))
    if @post.save
      redirect_to @post
    else
      render 'new'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @user = User.find(current_user.id)
    if @user.admin
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'users/new'
    end

  end

  def makeAdmin

    @user = User.find(params[:nesto])
    puts "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    puts @user.admin
    if @user.admin
      @user.update(admin:false)
    else
      @user.update(admin: true)
    end

    puts @user.admin

    redirect_to users_path
  end

  def obrisi
    @user = User.find(params[:nesto])
    @korisnik = User.find(current_user.id)
    if @korisnik.admin
      @user.destroy
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dokuments_helper.rb
module DokumentsHelper
end

app/helpers/izmenas_helper.rb
module IzmenasHelper
end

app/helpers/organizacijas_helper.rb
module OrganizacijasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/primedbas_helper.rb
module PrimedbasHelper
end

app/helpers/tranzakcijas_helper.rb
module TranzakcijasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.erb
<hr>
<div class="box">
  <article class="media">
    <div class="media-content">
      <div class="content">
        <p>
          <strong><%= comment.name %></strong>
          <br>
          <br>
          <%=comment.content %>
        </p>
      </div>
    </div>

    <%= link_to "Delete" , [comment.post, comment], method: :delete, class: "button is-danger", data:{confirm:"Da li si 100% siguran?"} %>

  </article>


</div>

app/views/comments/_form.erb
  <%= simple_form_for([@post, @post.comments.build]) do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :name, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary" %>
  <% end %>

app/views/izmenas/edit.erb
<h1>edit stranica</h1>

app/views/izmenas/show.erb
<style>
  ins {
    text-decoration: none;
    background-color: #d4fcbc;
  }

  del {
    text-decoration: line-through;
    background-color: #fbb6c2;
    color: #555;
  }
</style>

<section class="section">
   <div class="container">
     <h1>Izmene za selektovan dokument : </h1>
     <% brojac = 0 %>
    <% @izmenas.each do |izmena|  %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content navbar">
              <p class="title is-4 is-right"> <%= izmena.title %></p>
              <p class=" navbar-end">
                <%#= link_to "Rollback", rollback_dokument_izmenas_path, class:"navbar-item" %>
                <%= link_to "Rollback", rollback_dokument_izmenas_path(nesto:izmena), method: post, class:"button is-danger" %>
              </p>
            </div>
          </div>
          <div class="content">
            <%if brojac != 0 %>

              <%end %>
            <% puts brojac %>
            <% brojac+=1 %>
            <%= izmena.content %>
            <% staraIzmena = izmena %>

            <p id="output"></p>

          </div>

          <!--          <div class="comment-count">-->
          <!--            <span class="tag is-rounded"> <%## comment.count %></span>-->
          <!--          </div>-->
        </div>
      </div>
      <br>

    <% end %>
  </div>
</section>

app/views/posts/_form.erb
<div class="section">
  <%= simple_form_for @post do |f| %>
    <div class="field">
      <div class="control">
        <%= f.input :title, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <div class="field">
      <div class="control">
        <%= f.input :content, input_html: { class: 'textarea' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <%= f.button :submit, class: "button is-primary" %>
  <% end %>
</div>

app/views/posts/edit.erb
<%= render 'form' %>

app/views/posts/index.erb
<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<section class="section">
  <div class="container">
    <% @posts.each do |post|  %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"> <%= link_to post.title, post %></p>
            </div>
          </div>
          <div class="content">
            <%= post.content %>
          </div>
<!--          <div class="comment-count">-->
<!--            <span class="tag is-rounded"> <%## comment.count %></span>-->
<!--          </div>-->
        </div>
      </div>
      <br>

    <% end %>
  </div>
</section>

<div class="container">

  <div class="is-center">

    <%= will_paginate @posts, class:  "digg_pagination"  %>

  </div>
</div>

<style>


  .digg_pagination {

    background: white;
    cursor: default;
    text-align: center;
    /* self-clearing method: */ }
  .digg_pagination a, .digg_pagination span, .digg_pagination em {
    padding: 0.2em 0.5em;
    display: block;
    float: left;
    margin-right: 1px; }
  .digg_pagination .disabled {
    color: #999999;
    border: 1px solid #dddddd; }
  .digg_pagination .current {
    font-style: normal;
    font-weight: bold;
    background: #2e6ab1;
    color: white;
    border: 1px solid #2e6ab1; }
  .digg_pagination a {
    text-decoration: none;
    color: #105cb6;
    border: 1px solid #9aafe5; }
  .digg_pagination a:hover, .digg_pagination a:focus {
    color: #000033;
    border-color: #000033; }
  .digg_pagination .page_info {
    background: #2e6ab1;
    color: white;
    padding: 0.4em 0.6em;
    width: 22em;
    margin-bottom: 0.3em;
    text-align: center; }
  .digg_pagination .page_info b {
    color: #000033;
    background: #6aa6ed;
    padding: 0.1em 0.25em; }
  .digg_pagination:after {
    content: ".";
    display: block;
    height: 0;
    clear: both;
    visibility: hidden; }
  * html .digg_pagination {
    height: 1%; }
  *:first-child + html .digg_pagination {
    overflow: hidden; }
</style>

app/views/posts/new.erb
<h1 class="title"> Ovo je new stranica</h1>


<%= render 'form' %>

app/views/posts/show.erb
<section class="section">
  <div class="container">

    <nav class="level">
      <div class="level-left">
        <p class="level-item">
          <strong>Opcije</strong>
        </p>
      </div>

      <div class="level-right">
        <p class="level-item">
          <%=  link_to "Edit", edit_post_path(@post), class: "button" %>
        </p>
        <p class="level-item">
          <%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Da li ste sigurni?"}, class:"button is-danger" %>
        </p>
      </div>
    </nav>
    <hr>


    <h2 class="title"><%= @post.title %></h2>
    <div class="content">
      <%= @post.content  %>
    </div>
  </div>
</section>

<section class="comments">

  <div class="container">
    <h2 class="subtitle is-5"><strong> <%= @post.comments.count %> </strong> Komentara</h2>
    <%= render @post.comments %>
    <div class="comment-form">
      <hr>
      <h3 class="subtitle is-3"> Napisi nesto!</h3>
      <%= render 'comments/form' %>
    </div>
  </div>
</section>

app/views/users/_form.html.erb
<%#= form_for :session, url: session_path do |form| %>
<!--  <div class="text-field">-->
    <%#= form.label :email %>
    <%#= form.text_field :email, type: 'email' %>
<!--  </div>-->

<!--  <div class="password-field">-->
    <%#= form.label :password %>
    <%#= form.password_field :password %>
<!--  </div>-->

<!--  <div class="submit-field">-->
    <%#= form.submit %>
<!--  </div>-->


<%# end %>


<div class="section">
  <%= simple_form_for @user do |f| %>
    <div class="text-field">
      <div class="control">
        <%= f.input :email, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>

    <div class="password-field">
      <div class="control">
        <%= f.input :password, input_html: { class: 'input' }, wrapper: false, label_html: {class: 'label'} %>
      </div>
    </div>
    <br>


    <br>
    <%= f.button :submit, class: "button is-primary" %>

    <br>

    <div class="other-links">
      <% if Clearance.configuration.allow_sign_up? %>
        <%= link_to t(".sign_in"), sign_in_path %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/users/index.erb
<section class="section">
  <div class="container">
    <% @users.each do |user|  %>
      <% if user.id != current_user.id %>
      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4"> <%=  user.email %></p>
            </div>
          </div>
          <div class="content">
            <%= user.password %>

          </div>
          <div class="nav">
            <%= link_to "Delete", obrisi_users_path(nesto:user), method: :delete, data: {confirm: "Da li ste sigurni?"}, class:"button is-danger dugmici" %>

            <%= link_to "Toggle Admin", makeAdmin_users_path(nesto:user), method: :post, data: {confirm: "Da li ste sigurni?"}, class:"button is-info dugmici" %>
          </div>

        </div>
      </div>
      <br>
    <%end %>
    <% end %>
  </div>
</section>

app/views/users/new.html.erb
<div class="container">
  <div class="media">
    <section>

      <div id="clearance" class="sign-in">
        <h2><%= t(".title") %></h2>

        <%= render partial: '/users/form' %>

      </div>

    </section>
  </div>
</div>