config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :posts do
    resources :comments
  end

  resources :dokuments do
    collection do
        post ':id/addKorisnik', :to =>  'dokuments#addKorisnik', :as => :addKorisnik

    end
    resource :izmenas do
      collection do
        post "rollback", :to=> 'izmenas#rollback', :as => :rollback
      end
    end
  end

  resources :users do
    collection do
      delete "obrisiUsera", :to=> 'users#obrisi', :as => :obrisi
      post "makeAdmin", :to=> 'users#makeAdmin', :as => :makeAdmin

    end
  end



  root "posts#index"

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
    #

    can :read, :all # permissions for every user, even if not logged in
    if user.present?  # additional permissions for logged in users (they can manage their posts)
      can :manage, Post, user_id: user.id
      if user.admin?  # additional permissions for administrators
        can :manage, :all
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/dokument.rb
class Dokument < ApplicationRecord
  has_and_belongs_to_many :users
  has_many :tranzakcijas
  has_many :primedbas
  has_many :izmenas
end

app/models/izmena.rb
class Izmena < ApplicationRecord
  belongs_to :user
  belongs_to :dokument
end

app/models/organizacija.rb
class Organizacija < ApplicationRecord
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments

  belongs_to :user

end

app/models/primedba.rb
class Primedba < ApplicationRecord
  belongs_to :user
  belongs_to :dokument
end

app/models/tranzakcija.rb
class Tranzakcija < ApplicationRecord
  belongs_to :user
  has_one :dokument
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :posts
  has_and_belongs_to_many :dokuments
  has_many :primedbas
  has_many :izmenas

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.paginate(page: params[:page], per_page: 2)
  end

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    #@user = User.find(params[:user_id])
    #@post = current_user.posts.new(params[:post])
    #@post = current_user.posts.find(post_params[:id])
    @user = User.find(current_user.id)
    @post = @user.posts.create(post_params.permit(:title, :content))
    if @post.save
      redirect_to @post
    else
      render 'new'
    end

  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @user = User.find(current_user.id)
    if @user.admin
      @users = User.all
    else
      redirect_to root_path
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render 'users/new'
    end

  end

  def makeAdmin

    @user = User.find(params[:nesto])
    puts "AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    puts @user.admin
    if @user.admin
      @user.update(admin:false)
    else
      @user.update(admin: true)
    end

    puts @user.admin

    redirect_to users_path
  end

  def obrisi
    @user = User.find(params[:nesto])
    @korisnik = User.find(current_user.id)
    if @korisnik.admin
      @user.destroy
      redirect_to users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dokuments_helper.rb
module DokumentsHelper
end

app/helpers/izmenas_helper.rb
module IzmenasHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/primedbas_helper.rb
module PrimedbasHelper
end

app/helpers/tranzakcijas_helper.rb
module TranzakcijasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyProjekat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

  <section class="hero is-dark is-small">
    <!-- Hero head: will stick at the top -->
    <div class="hero-head">
      <nav class="navbar">
        <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item">
              <img src="http://pixelartmaker.com/art/2b2b92fca4e146e.png" alt="Logo">
            </a>
            <span class="navbar-burger burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
          </div>
          <div id="navbarMenuHeroA" class="navbar-menu">
            <div class="navbar">
              <%= link_to "Home", posts_path, class:"navbar-item" %>
              <% if signed_in? %>
                <%= link_to "Napravi novi dokument", new_dokument_path, class:"navbar-item" %>

                <%= link_to "Lista dokumenata usera", dokuments_path, class:"navbar-item" %>
              <%end %>



                </div>
                <div class="navbar-end is-right">
                  <% if signed_in? %>

                    <p class="field-label" id="singingovan">Signed in as: <%= current_user.email %> &nbsp &nbsp &nbsp</p>

                    <%= button_to 'Sign out', sign_out_path, method: :delete, class:"button" %>


                  <% else %>

                      <%= link_to 'Sign in', sign_in_path , class:"button dugmic"%>
                      <%= link_to 'Sign up', sign_up_path ,class:"button dugmic" %>



                  <% end %>



                </div>

            </div>
          </div>
      </nav>
    </div>

    <!-- Hero content: will be in the middle -->
<!--    <div class="hero-body">-->
<!--      <div class="container has-text-centered">-->
<!--        <h1 class="title">-->
<!--          Title-->
<!--        </h1>-->
<!--        <h2 class="subtitle">-->
<!--          Subtitle-->
<!--        </h2>-->
<!--      </div>-->
<!--    </div>-->

    <!-- Hero footer: will stick at the bottom -->
    <div class="hero-foot">
      <nav class="tabs">
        <div class="container">
<!--          <ul>-->
<!--            <li class="is-active"><a>Overview</a></li>-->
<!--            <li><a>Modifiers</a></li>-->
<!--            <li><a>Grid</a></li>-->
<!--            <li><a>Elements</a></li>-->
<!--            <li><a>Components</a></li>-->
<!--            <li><a>Layout</a></li>-->
<!--          </ul>-->
        </div>

      </nav>




    </div>
  </section>


    <%= yield %>
  </body>
</html>
<style>

  #singingovan{
    margin-top: 10px
  }
    .dugmic{
      margin: 10px;
    }
</style>